# Read the documentation at https://github.com/thephpleague/flysystem-bundle/blob/master/docs/1-getting-started.md
flysystem:
    storages:
        uploads.storage:
            adapter: 'aws'
            options:
                client: 's3.client'
                bucket: '%env(AWS_BUCKET)%'
                prefix: ''
